/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from 'zod';
import * as generated from './supabase.zod.schemas';
export type AttributeType = z.infer<typeof generated.publicAttributeTypeSchema>;
export type Continents = z.infer<typeof generated.publicContinentsSchema>;
export type Entity = z.infer<typeof generated.publicEntitySchema>;
export type Packingtype = z.infer<typeof generated.publicPackingtypeSchema>;
export type RegionType = z.infer<typeof generated.publicRegionTypeSchema>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type AdClientRow = z.infer<typeof generated.adClientRowSchema>;
export type AdClientInsert = z.infer<typeof generated.adClientInsertSchema>;
export type AdClientUpdate = z.infer<typeof generated.adClientUpdateSchema>;
export type AdClientRelationships = z.infer<typeof generated.adClientRelationshipsSchema>;
export type AdLanguageRow = z.infer<typeof generated.adLanguageRowSchema>;
export type AdLanguageInsert = z.infer<typeof generated.adLanguageInsertSchema>;
export type AdLanguageUpdate = z.infer<typeof generated.adLanguageUpdateSchema>;
export type AdUserRow = z.infer<typeof generated.adUserRowSchema>;
export type AdUserInsert = z.infer<typeof generated.adUserInsertSchema>;
export type AdUserUpdate = z.infer<typeof generated.adUserUpdateSchema>;
export type AdUserRelationships = z.infer<typeof generated.adUserRelationshipsSchema>;
export type CBpartnerRow = z.infer<typeof generated.cBpartnerRowSchema>;
export type CBpartnerInsert = z.infer<typeof generated.cBpartnerInsertSchema>;
export type CBpartnerUpdate = z.infer<typeof generated.cBpartnerUpdateSchema>;
export type CBpartnerRelationships = z.infer<typeof generated.cBpartnerRelationshipsSchema>;
export type CBpartnerLocationRow = z.infer<typeof generated.cBpartnerLocationRowSchema>;
export type CBpartnerLocationInsert = z.infer<typeof generated.cBpartnerLocationInsertSchema>;
export type CBpartnerLocationUpdate = z.infer<typeof generated.cBpartnerLocationUpdateSchema>;
export type CBpartnerLocationRelationships = z.infer<
	typeof generated.cBpartnerLocationRelationshipsSchema
>;
export type CChannelRow = z.infer<typeof generated.cChannelRowSchema>;
export type CChannelInsert = z.infer<typeof generated.cChannelInsertSchema>;
export type CChannelUpdate = z.infer<typeof generated.cChannelUpdateSchema>;
export type CChannelMapRow = z.infer<typeof generated.cChannelMapRowSchema>;
export type CChannelMapInsert = z.infer<typeof generated.cChannelMapInsertSchema>;
export type CChannelMapUpdate = z.infer<typeof generated.cChannelMapUpdateSchema>;
export type CChannelMapRelationships = z.infer<typeof generated.cChannelMapRelationshipsSchema>;
export type CChannelMapBpartnerRow = z.infer<typeof generated.cChannelMapBpartnerRowSchema>;
export type CChannelMapBpartnerInsert = z.infer<typeof generated.cChannelMapBpartnerInsertSchema>;
export type CChannelMapBpartnerUpdate = z.infer<typeof generated.cChannelMapBpartnerUpdateSchema>;
export type CChannelMapBpartnerRelationships = z.infer<
	typeof generated.cChannelMapBpartnerRelationshipsSchema
>;
export type CChannelMapBrandRow = z.infer<typeof generated.cChannelMapBrandRowSchema>;
export type CChannelMapBrandInsert = z.infer<typeof generated.cChannelMapBrandInsertSchema>;
export type CChannelMapBrandUpdate = z.infer<typeof generated.cChannelMapBrandUpdateSchema>;
export type CChannelMapBrandRelationships = z.infer<
	typeof generated.cChannelMapBrandRelationshipsSchema
>;
export type CChannelMapCategoryRow = z.infer<typeof generated.cChannelMapCategoryRowSchema>;
export type CChannelMapCategoryInsert = z.infer<typeof generated.cChannelMapCategoryInsertSchema>;
export type CChannelMapCategoryUpdate = z.infer<typeof generated.cChannelMapCategoryUpdateSchema>;
export type CChannelMapCategoryRelationships = z.infer<
	typeof generated.cChannelMapCategoryRelationshipsSchema
>;
export type CChannelMapProductRow = z.infer<typeof generated.cChannelMapProductRowSchema>;
export type CChannelMapProductInsert = z.infer<typeof generated.cChannelMapProductInsertSchema>;
export type CChannelMapProductUpdate = z.infer<typeof generated.cChannelMapProductUpdateSchema>;
export type CChannelMapProductRelationships = z.infer<
	typeof generated.cChannelMapProductRelationshipsSchema
>;
export type CChannelMapTaxcategoryRow = z.infer<typeof generated.cChannelMapTaxcategoryRowSchema>;
export type CChannelMapTaxcategoryInsert = z.infer<
	typeof generated.cChannelMapTaxcategoryInsertSchema
>;
export type CChannelMapTaxcategoryUpdate = z.infer<
	typeof generated.cChannelMapTaxcategoryUpdateSchema
>;
export type CChannelMapTaxcategoryRelationships = z.infer<
	typeof generated.cChannelMapTaxcategoryRelationshipsSchema
>;
export type CChannelMapUomRow = z.infer<typeof generated.cChannelMapUomRowSchema>;
export type CChannelMapUomInsert = z.infer<typeof generated.cChannelMapUomInsertSchema>;
export type CChannelMapUomUpdate = z.infer<typeof generated.cChannelMapUomUpdateSchema>;
export type CChannelMapUomRelationships = z.infer<
	typeof generated.cChannelMapUomRelationshipsSchema
>;
export type CChannelMapWarehouseRow = z.infer<typeof generated.cChannelMapWarehouseRowSchema>;
export type CChannelMapWarehouseInsert = z.infer<typeof generated.cChannelMapWarehouseInsertSchema>;
export type CChannelMapWarehouseUpdate = z.infer<typeof generated.cChannelMapWarehouseUpdateSchema>;
export type CChannelMapWarehouseRelationships = z.infer<
	typeof generated.cChannelMapWarehouseRelationshipsSchema
>;
export type CCurrencyRow = z.infer<typeof generated.cCurrencyRowSchema>;
export type CCurrencyInsert = z.infer<typeof generated.cCurrencyInsertSchema>;
export type CCurrencyUpdate = z.infer<typeof generated.cCurrencyUpdateSchema>;
export type CTaxRow = z.infer<typeof generated.cTaxRowSchema>;
export type CTaxInsert = z.infer<typeof generated.cTaxInsertSchema>;
export type CTaxUpdate = z.infer<typeof generated.cTaxUpdateSchema>;
export type CTaxRelationships = z.infer<typeof generated.cTaxRelationshipsSchema>;
export type CTaxcategoryRow = z.infer<typeof generated.cTaxcategoryRowSchema>;
export type CTaxcategoryInsert = z.infer<typeof generated.cTaxcategoryInsertSchema>;
export type CTaxcategoryUpdate = z.infer<typeof generated.cTaxcategoryUpdateSchema>;
export type CUomRow = z.infer<typeof generated.cUomRowSchema>;
export type CUomInsert = z.infer<typeof generated.cUomInsertSchema>;
export type CUomUpdate = z.infer<typeof generated.cUomUpdateSchema>;
export type CUomConversionRow = z.infer<typeof generated.cUomConversionRowSchema>;
export type CUomConversionInsert = z.infer<typeof generated.cUomConversionInsertSchema>;
export type CUomConversionUpdate = z.infer<typeof generated.cUomConversionUpdateSchema>;
export type CUomConversionRelationships = z.infer<
	typeof generated.cUomConversionRelationshipsSchema
>;
export type ContactTypesRow = z.infer<typeof generated.contactTypesRowSchema>;
export type ContactTypesInsert = z.infer<typeof generated.contactTypesInsertSchema>;
export type ContactTypesUpdate = z.infer<typeof generated.contactTypesUpdateSchema>;
export type ContactsRow = z.infer<typeof generated.contactsRowSchema>;
export type ContactsInsert = z.infer<typeof generated.contactsInsertSchema>;
export type ContactsUpdate = z.infer<typeof generated.contactsUpdateSchema>;
export type DocGeneratedDocumentRow = z.infer<typeof generated.docGeneratedDocumentRowSchema>;
export type DocGeneratedDocumentInsert = z.infer<typeof generated.docGeneratedDocumentInsertSchema>;
export type DocGeneratedDocumentUpdate = z.infer<typeof generated.docGeneratedDocumentUpdateSchema>;
export type DocGeneratedDocumentRelationships = z.infer<
	typeof generated.docGeneratedDocumentRelationshipsSchema
>;
export type DocTemplateRow = z.infer<typeof generated.docTemplateRowSchema>;
export type DocTemplateInsert = z.infer<typeof generated.docTemplateInsertSchema>;
export type DocTemplateUpdate = z.infer<typeof generated.docTemplateUpdateSchema>;
export type LCountriesRow = z.infer<typeof generated.lCountriesRowSchema>;
export type LCountriesInsert = z.infer<typeof generated.lCountriesInsertSchema>;
export type LCountriesUpdate = z.infer<typeof generated.lCountriesUpdateSchema>;
export type LCountryRow = z.infer<typeof generated.lCountryRowSchema>;
export type LCountryInsert = z.infer<typeof generated.lCountryInsertSchema>;
export type LCountryUpdate = z.infer<typeof generated.lCountryUpdateSchema>;
export type LCountryRelationships = z.infer<typeof generated.lCountryRelationshipsSchema>;
export type LLocalesRow = z.infer<typeof generated.lLocalesRowSchema>;
export type LLocalesInsert = z.infer<typeof generated.lLocalesInsertSchema>;
export type LLocalesUpdate = z.infer<typeof generated.lLocalesUpdateSchema>;
export type LLocalesRelationships = z.infer<typeof generated.lLocalesRelationshipsSchema>;
export type LLocationRow = z.infer<typeof generated.lLocationRowSchema>;
export type LLocationInsert = z.infer<typeof generated.lLocationInsertSchema>;
export type LLocationUpdate = z.infer<typeof generated.lLocationUpdateSchema>;
export type LLocationRelationships = z.infer<typeof generated.lLocationRelationshipsSchema>;
export type LMunicipalityRow = z.infer<typeof generated.lMunicipalityRowSchema>;
export type LMunicipalityInsert = z.infer<typeof generated.lMunicipalityInsertSchema>;
export type LMunicipalityUpdate = z.infer<typeof generated.lMunicipalityUpdateSchema>;
export type LMunicipalityRelationships = z.infer<typeof generated.lMunicipalityRelationshipsSchema>;
export type LPostalCodeRow = z.infer<typeof generated.lPostalCodeRowSchema>;
export type LPostalCodeInsert = z.infer<typeof generated.lPostalCodeInsertSchema>;
export type LPostalCodeUpdate = z.infer<typeof generated.lPostalCodeUpdateSchema>;
export type LPostalCodeRelationships = z.infer<typeof generated.lPostalCodeRelationshipsSchema>;
export type LRegionRow = z.infer<typeof generated.lRegionRowSchema>;
export type LRegionInsert = z.infer<typeof generated.lRegionInsertSchema>;
export type LRegionUpdate = z.infer<typeof generated.lRegionUpdateSchema>;
export type LRegionRelationships = z.infer<typeof generated.lRegionRelationshipsSchema>;
export type MAttributeRow = z.infer<typeof generated.mAttributeRowSchema>;
export type MAttributeInsert = z.infer<typeof generated.mAttributeInsertSchema>;
export type MAttributeUpdate = z.infer<typeof generated.mAttributeUpdateSchema>;
export type MAttributeRelationships = z.infer<typeof generated.mAttributeRelationshipsSchema>;
export type MAttributeGroupRow = z.infer<typeof generated.mAttributeGroupRowSchema>;
export type MAttributeGroupInsert = z.infer<typeof generated.mAttributeGroupInsertSchema>;
export type MAttributeGroupUpdate = z.infer<typeof generated.mAttributeGroupUpdateSchema>;
export type MAttributeOptionRow = z.infer<typeof generated.mAttributeOptionRowSchema>;
export type MAttributeOptionInsert = z.infer<typeof generated.mAttributeOptionInsertSchema>;
export type MAttributeOptionUpdate = z.infer<typeof generated.mAttributeOptionUpdateSchema>;
export type MAttributeOptionRelationships = z.infer<
	typeof generated.mAttributeOptionRelationshipsSchema
>;
export type MAttributesetRow = z.infer<typeof generated.mAttributesetRowSchema>;
export type MAttributesetInsert = z.infer<typeof generated.mAttributesetInsertSchema>;
export type MAttributesetUpdate = z.infer<typeof generated.mAttributesetUpdateSchema>;
export type MAttributesetAttributeRow = z.infer<typeof generated.mAttributesetAttributeRowSchema>;
export type MAttributesetAttributeInsert = z.infer<
	typeof generated.mAttributesetAttributeInsertSchema
>;
export type MAttributesetAttributeUpdate = z.infer<
	typeof generated.mAttributesetAttributeUpdateSchema
>;
export type MAttributesetAttributeRelationships = z.infer<
	typeof generated.mAttributesetAttributeRelationshipsSchema
>;
export type MDiscountschemaRow = z.infer<typeof generated.mDiscountschemaRowSchema>;
export type MDiscountschemaInsert = z.infer<typeof generated.mDiscountschemaInsertSchema>;
export type MDiscountschemaUpdate = z.infer<typeof generated.mDiscountschemaUpdateSchema>;
export type MLocatorRow = z.infer<typeof generated.mLocatorRowSchema>;
export type MLocatorInsert = z.infer<typeof generated.mLocatorInsertSchema>;
export type MLocatorUpdate = z.infer<typeof generated.mLocatorUpdateSchema>;
export type MLocatorRelationships = z.infer<typeof generated.mLocatorRelationshipsSchema>;
export type MPricelistRow = z.infer<typeof generated.mPricelistRowSchema>;
export type MPricelistInsert = z.infer<typeof generated.mPricelistInsertSchema>;
export type MPricelistUpdate = z.infer<typeof generated.mPricelistUpdateSchema>;
export type MPricelistRelationships = z.infer<typeof generated.mPricelistRelationshipsSchema>;
export type MPricelistVersionRow = z.infer<typeof generated.mPricelistVersionRowSchema>;
export type MPricelistVersionInsert = z.infer<typeof generated.mPricelistVersionInsertSchema>;
export type MPricelistVersionUpdate = z.infer<typeof generated.mPricelistVersionUpdateSchema>;
export type MPricelistVersionRelationships = z.infer<
	typeof generated.mPricelistVersionRelationshipsSchema
>;
export type MProductRow = z.infer<typeof generated.mProductRowSchema>;
export type MProductInsert = z.infer<typeof generated.mProductInsertSchema>;
export type MProductUpdate = z.infer<typeof generated.mProductUpdateSchema>;
export type MProductRelationships = z.infer<typeof generated.mProductRelationshipsSchema>;
export type MProductAttributeOptionRow = z.infer<typeof generated.mProductAttributeOptionRowSchema>;
export type MProductAttributeOptionInsert = z.infer<
	typeof generated.mProductAttributeOptionInsertSchema
>;
export type MProductAttributeOptionUpdate = z.infer<
	typeof generated.mProductAttributeOptionUpdateSchema
>;
export type MProductAttributeOptionRelationships = z.infer<
	typeof generated.mProductAttributeOptionRelationshipsSchema
>;
export type MProductAttributeValueRow = z.infer<typeof generated.mProductAttributeValueRowSchema>;
export type MProductAttributeValueInsert = z.infer<
	typeof generated.mProductAttributeValueInsertSchema
>;
export type MProductAttributeValueUpdate = z.infer<
	typeof generated.mProductAttributeValueUpdateSchema
>;
export type MProductAttributeValueRelationships = z.infer<
	typeof generated.mProductAttributeValueRelationshipsSchema
>;
export type MProductBrandsRow = z.infer<typeof generated.mProductBrandsRowSchema>;
export type MProductBrandsInsert = z.infer<typeof generated.mProductBrandsInsertSchema>;
export type MProductBrandsUpdate = z.infer<typeof generated.mProductBrandsUpdateSchema>;
export type MProductCategoryRow = z.infer<typeof generated.mProductCategoryRowSchema>;
export type MProductCategoryInsert = z.infer<typeof generated.mProductCategoryInsertSchema>;
export type MProductCategoryUpdate = z.infer<typeof generated.mProductCategoryUpdateSchema>;
export type MProductCategoryRelationships = z.infer<
	typeof generated.mProductCategoryRelationshipsSchema
>;
export type MProductPackingRow = z.infer<typeof generated.mProductPackingRowSchema>;
export type MProductPackingInsert = z.infer<typeof generated.mProductPackingInsertSchema>;
export type MProductPackingUpdate = z.infer<typeof generated.mProductPackingUpdateSchema>;
export type MProductPackingRelationships = z.infer<
	typeof generated.mProductPackingRelationshipsSchema
>;
export type MProductPoRow = z.infer<typeof generated.mProductPoRowSchema>;
export type MProductPoInsert = z.infer<typeof generated.mProductPoInsertSchema>;
export type MProductPoUpdate = z.infer<typeof generated.mProductPoUpdateSchema>;
export type MProductPoRelationships = z.infer<typeof generated.mProductPoRelationshipsSchema>;
export type MProductpriceRow = z.infer<typeof generated.mProductpriceRowSchema>;
export type MProductpriceInsert = z.infer<typeof generated.mProductpriceInsertSchema>;
export type MProductpriceUpdate = z.infer<typeof generated.mProductpriceUpdateSchema>;
export type MProductpriceRelationships = z.infer<typeof generated.mProductpriceRelationshipsSchema>;
export type MReplenishRow = z.infer<typeof generated.mReplenishRowSchema>;
export type MReplenishInsert = z.infer<typeof generated.mReplenishInsertSchema>;
export type MReplenishUpdate = z.infer<typeof generated.mReplenishUpdateSchema>;
export type MReplenishRelationships = z.infer<typeof generated.mReplenishRelationshipsSchema>;
export type MStorageonhandRow = z.infer<typeof generated.mStorageonhandRowSchema>;
export type MStorageonhandInsert = z.infer<typeof generated.mStorageonhandInsertSchema>;
export type MStorageonhandUpdate = z.infer<typeof generated.mStorageonhandUpdateSchema>;
export type MStorageonhandRelationships = z.infer<
	typeof generated.mStorageonhandRelationshipsSchema
>;
export type MSubstituteRow = z.infer<typeof generated.mSubstituteRowSchema>;
export type MSubstituteInsert = z.infer<typeof generated.mSubstituteInsertSchema>;
export type MSubstituteUpdate = z.infer<typeof generated.mSubstituteUpdateSchema>;
export type MSubstituteRelationships = z.infer<typeof generated.mSubstituteRelationshipsSchema>;
export type MWarehouseRow = z.infer<typeof generated.mWarehouseRowSchema>;
export type MWarehouseInsert = z.infer<typeof generated.mWarehouseInsertSchema>;
export type MWarehouseUpdate = z.infer<typeof generated.mWarehouseUpdateSchema>;
export type PricingRulesRow = z.infer<typeof generated.pricingRulesRowSchema>;
export type PricingRulesInsert = z.infer<typeof generated.pricingRulesInsertSchema>;
export type PricingRulesUpdate = z.infer<typeof generated.pricingRulesUpdateSchema>;
export type WBasketRow = z.infer<typeof generated.wBasketRowSchema>;
export type WBasketInsert = z.infer<typeof generated.wBasketInsertSchema>;
export type WBasketUpdate = z.infer<typeof generated.wBasketUpdateSchema>;
export type WBasketRelationships = z.infer<typeof generated.wBasketRelationshipsSchema>;
export type WBasketlineRow = z.infer<typeof generated.wBasketlineRowSchema>;
export type WBasketlineInsert = z.infer<typeof generated.wBasketlineInsertSchema>;
export type WBasketlineUpdate = z.infer<typeof generated.wBasketlineUpdateSchema>;
export type WBasketlineRelationships = z.infer<typeof generated.wBasketlineRelationshipsSchema>;
export type BulkUpdateProductPoArgs = z.infer<typeof generated.publicBulkUpdateProductPoArgsSchema>;
export type BulkUpdateProductPoReturns = z.infer<
	typeof generated.publicBulkUpdateProductPoReturnsSchema
>;
export type BulkUpdateProductpriceArgs = z.infer<
	typeof generated.publicBulkUpdateProductpriceArgsSchema
>;
export type BulkUpdateProductpriceReturns = z.infer<
	typeof generated.publicBulkUpdateProductpriceReturnsSchema
>;
export type BulkUpdateProductsArgs = z.infer<typeof generated.publicBulkUpdateProductsArgsSchema>;
export type BulkUpdateProductsReturns = z.infer<
	typeof generated.publicBulkUpdateProductsReturnsSchema
>;
export type BulkUpdateStorageonhandArgs = z.infer<
	typeof generated.publicBulkUpdateStorageonhandArgsSchema
>;
export type BulkUpdateStorageonhandReturns = z.infer<
	typeof generated.publicBulkUpdateStorageonhandReturnsSchema
>;
export type CheckAttributesMatchArgs = z.infer<
	typeof generated.publicCheckAttributesMatchArgsSchema
>;
export type CheckAttributesMatchReturns = z.infer<
	typeof generated.publicCheckAttributesMatchReturnsSchema
>;
export type DeleteAvatarArgs = z.infer<typeof generated.publicDeleteAvatarArgsSchema>;
export type DeleteAvatarReturns = z.infer<typeof generated.publicDeleteAvatarReturnsSchema>;
export type DeleteStorageObjectArgs = z.infer<typeof generated.publicDeleteStorageObjectArgsSchema>;
export type DeleteStorageObjectReturns = z.infer<
	typeof generated.publicDeleteStorageObjectReturnsSchema
>;
export type FindApplicablePricingRulesArgs = z.infer<
	typeof generated.publicFindApplicablePricingRulesArgsSchema
>;
export type FindApplicablePricingRulesReturns = z.infer<
	typeof generated.publicFindApplicablePricingRulesReturnsSchema
>;
export type GetLocalizedLookupArgs = z.infer<typeof generated.publicGetLocalizedLookupArgsSchema>;
export type GetLocalizedLookupReturns = z.infer<
	typeof generated.publicGetLocalizedLookupReturnsSchema
>;
export type GetPriceFormulaVariablesArgs = z.infer<
	typeof generated.publicGetPriceFormulaVariablesArgsSchema
>;
export type GetPriceFormulaVariablesReturns = z.infer<
	typeof generated.publicGetPriceFormulaVariablesReturnsSchema
>;
export type GetProductAttributesArgs = z.infer<
	typeof generated.publicGetProductAttributesArgsSchema
>;
export type GetProductAttributesReturns = z.infer<
	typeof generated.publicGetProductAttributesReturnsSchema
>;
export type IsValidGtinArgs = z.infer<typeof generated.publicIsValidGtinArgsSchema>;
export type IsValidGtinReturns = z.infer<typeof generated.publicIsValidGtinReturnsSchema>;
export type SearchProductsArgs = z.infer<typeof generated.publicSearchProductsArgsSchema>;
export type SearchProductsReturns = z.infer<typeof generated.publicSearchProductsReturnsSchema>;
